version: "3"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "12345:80"
    volumes:
      - /app/node_modules
      - ../frontend:/app
  tests:
      build:
        context: .
        dockerfile: Dockerfile
      volumes:
          - /app/node_modules
          - ../frontend:/app
      